### ISSUE TITLE
TypeScript errors when importing package

### ISSUE THREAD

**Issue by dank074** [ektotv/xmltv#8]
When I attempt to import the package into my TypeScript project using 
```ts 
import { parseXmltv } from "@iptv/xmltv"
``` 
I get the following error:
```
Could not find a declaration file for module '@iptv/xmltv'. 'c:/Users/***/Documents/my-application/node_modules/@iptv/xmltv/dist/xmltv.js' implicitly has an 'any' type.
  There are types at 'c:/Users/***/Documents/my-application/node_modules/@iptv/xmltv/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@iptv/xmltv' library may need to update its package.json or typings.ts(7016)
```

I found this in the TypeScript documentation while searching for a solution:

> It’s important to note that the CommonJS entrypoint and the ES module entrypoint each needs its own declaration file, even if the contents are the same between them. Every declaration file is interpreted either as a CommonJS module or as an ES module, based on its file extension and the "type" field of the package.json, and this detected module kind must match the module kind that Node will detect for the corresponding JavaScript file for type checking to be correct. Attempting to use a single .d.ts file to type both an ES module entrypoint and a CommonJS entrypoint will cause TypeScript to think only one of those entrypoints exists, causing compiler errors for users of the package
(https://www.typescriptlang.org/docs/handbook/esm-node.html)

**Comment by evoactivity** [comment]
Keeping this open until https://github.com/qmhc/vite-plugin-dts/issues/267 is fixed and we can generate the two different files.

**Comment by evoactivity** [comment]
Someones posted a nice workaround I can use here, should be able to get the types fully passing on https://arethetypeswrong.github.io/?p=%40iptv%2Fxmltv%400.1.6.

**Comment by evoactivity** [comment]
Types are now fully correct according to https://arethetypeswrong.github.io/?p=%40iptv%2Fxmltv%401.0.1 so I am closing this issue.
